# Generated by Django 5.0.4 on 2024-04-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0002_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Cars', 'Cars'), ('Phones', 'Phones'), ('Laptops', 'Laptops'), ('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Appliances', 'Appliances')], default='General', max_length=100),
        ),
    ]
