# Generated by Django 5.0.4 on 2024-04-16 17:48

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='product_pics/default.jpg', force_format=None, keep_meta=True, quality=100, scale=None, size=[400, 300], upload_to='product_pics'),
        ),
    ]
