# Generated by Django 5.0.6 on 2024-07-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0009_alter_inventory_bought_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='products',
            new_name='wishlist_products',
        ),
    ]
