# Generated by Django 5.0.6 on 2024-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0010_rename_products_inventory_wishlist_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
