# Generated by Django 5.0.4 on 2024-04-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
